branches:
  - master

build:
  image: php
  commands:
    - 'make syntax.checker'

deploy:
  ssh:
    host: magento.aplazame.com
    user: $$DEPLOY_USER
    commands:
      - 'cd $$RELEASE_PATH'
      - 'modgit update Magento_Aplazame'
      - 'chown -R www-data:www-data .'

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: 'drone'
    channel: 'developers'
    when:
      success: false
      failure: true
      change: true

  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASS
    recipients:
      - dev@aplazame.com
    when:
      success: false
      failure: true
      change: true
