<?php
/** @var Aplazame_Aplazame_Block_Product_Widget $this */
?>
<div
  data-aplazame-widget-instalments=""
  data-view="product"
  data-amount="<?php echo Aplazame_Sdk_Serializer_Decimal::fromFloat($this->getFinalPrice())->jsonSerialize(); ?>"
  data-currency="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>"
  data-article-id="<?php echo $this->getProduct()->getId(); ?>"
  data-option-legal-advice="<?php echo $this->getShowLegalAdvice(); ?>"
></div>
