<?php
/** @var Aplazame_Aplazame_Block_Product_Widget $this */
?>
<div
  <?php if ($this->getShowWidgetLegacy()) : ?>
    data-aplazame-widget-instalments=""
    data-view="product"
  <?php else : ?>
    data-aplazame-widget-instalments="v4"
    data-type="product"
    data-option-border-product="<?php echo $this->getShowBorder(); ?>"
    data-option-primary-color="<?php echo $this->getPrimaryColor(); ?>"
    data-option-layout="<?php echo $this->getWidgetLayout(); ?>"
    data-option-align="<?php echo $this->getWidgetAlign(); ?>"
  <?php endif; ?>
  data-amount="<?php echo Aplazame_Sdk_Serializer_Decimal::fromFloat($this->getFinalPrice())->jsonSerialize(); ?>"
  data-currency="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>"
  data-article-id="<?php echo $this->getProduct()->getId(); ?>"
  data-option-legal-advice="<?php echo $this->getShowLegalAdvice(); ?>"
  data-option-downpayment-info="<?php echo $this->getShowDownpaymentInfo(); ?>"
  data-option-out-of-limits="<?php echo $this->getOptionOutOfLimits(); ?>"
  <?php if ($this->getShowPayIn4()) : ?>
    data-pay-in-4=""
  <?php endif; ?>
  <?php if (! empty($this->getDefaultInstalments())) : ?>
    data-option-default-instalments="<?php echo $this->getDefaultInstalments(); ?>"
  <?php endif; ?>
></div>
