<fieldset class="form-list">
  <?php $_code=$this->getMethodCode() ?>
</fieldset>

<div id="payment_parent_form_aplazame" data-aplazame-payment-info="">
  <div id="payment_form_<?php echo $_code ?>" style="display:none;">
      <p class="aplazame_title" style="padding-left: 20px; padding-top: 8px;">
        Aplaza o fracciona tu compra con <a href="https://aplazame.com" target="_blank">Aplazame</a>.<br>
        Obtén financiación al instante sólo con tu Nombre y Apellidos, DNI/NIE, Teléfono y tarjeta de débito o crédito.<br>
        Sin comisiones ocultas ni letra pequeña.<br>
      </p>
  </div>
</div>

<script>
aplazame.button({
  id: "p_method_aplazame",
  amount: <?php echo $this->getTotal() ?>,
  currency: "EUR"
  // country: "ES"
});
</script>
