<?php
/** @var Aplazame_Aplazame_Block_Payment_Form $this */

$quote = $this->getQuote();

$buttonParams = array(
    'selector' => Mage::getStoreConfig('payment/aplazame/button'),
    'amount' => Aplazame_Sdk_Serializer_Decimal::fromFloat($quote->getGrandTotal())->jsonSerialize(),
    'currency' => $quote->getQuoteCurrencyCode(),
);
?>

<?php if ($instructions = $this->getInstructions()): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
                <?php echo nl2br($instructions) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>

<script>
aplazame.button(<?php echo json_encode($buttonParams) ?>);
</script>
