<html>
    <body style="margin: 0;">
        <script>
            aplazame.checkout(<?php echo json_encode($payment->getCheckoutSerializer(), 128) ?>);
        </script>

        <iframe src="<?php echo Mage::getUrl('', array('_secure'=>true)) ?>" style="position:fixed; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden;">
            Your browser doesnt support IFrames
        </iframe>
    </body>
</html>
