apiVersion: v1
kind: Pod
metadata:
spec:
  serviceAccountName: aplazame-appdeployer
  serviceAccount: aplazame-appdeployer
  securityContext:
    fsGroup: 1000
  containers:
  - name: node
    image: 666356151544.dkr.ecr.eu-central-1.amazonaws.com/tools/node:10.23.1_v2
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: 200Mi
        cpu: 200m
      limits:
        memory: 450Mi
        cpu: 500m